### ISSUE TITLE
Not able to connect a consul zk address through vpn 

### ISSUE THREAD

**Issue by PNarode** [huaban/erlzk#13]
Hello,

I am using the erlzk library in one of my app, which I am writing in Elixir. I am trying to connect to zk node using a consul address via vpn. It gives me error and I am not able to establish connection with the zknode. The error I am seeing is as follows:

I❤iex|2|▶▶▶ :erlzk.connect([{"pipe-apps-zookeeper-0.node.us-east-1-z.consul", 2181}], 30000)
{:ok, #PID<0.150.0>}
I❤iex|3|▶▶▶ 
02:21:22.525 [error] Resolving "pipe-apps-zookeeper-0.node.us-east-1-z.consul":2181 meet an error: :einval

02:21:22.525 [error] Connect fail: :no_available_server, will be try again after 1000s

02:21:23.519 [error] Connect fail: :no_available_server, will be try again after 1000s

02:21:24.520 [error] Connect fail: :no_available_server, will be try again after 1000s

##########################################################################
Also how do I send chroot while creating a zk connection. Because when I try to send it as below I am getting error:

I❤iex|3|▶▶▶ :erlzk.connect([{"pipe-apps-z-0.node.us-east-1-z.consul", 2181}], 30000, [{chroot, "/pipe-apps-general-kafka"}])
warning: variable "chroot" does not exist and is being expanded to "chroot()", please use parentheses to remove the ambiguity or change the variable name
  iex:3

Bug Bug ..!!** (CompileError) iex:3: undefined function chroot/0
Bug Bug ..!!    (stdlib) lists.erl:1354: :lists.mapfoldl/3

**Comment by zolazhou** [comment]
I think the problem have nothing to do with `erlzk`. It is a DNS resolving related problem, you may replace the hostname with a resolved IP address to test again. If that works, check out consul's documentation on how to use its built in DNS server within your environment.

And the second problem is because atom in Elixir should prefixed with colon, so erlang atom `chroot` should be `:chroot` like `:erlzk`.

**Comment by PNarode** [comment]
OK Thanks
