### ISSUE TITLE
When all ZK Servers fail to resolve, erlzk becomes stuck in a loop

### ISSUE THREAD

**Issue by davidrusu** [huaban/erlzk#15]
Thank your for your work on this project, we've enjoyed using it. We recently had this issue happen in one of our environments (thankfully not prod). The result was that our service hung and was not processing data.

## Steps to reproduce
(apologies for the elixir, my erlang vocab is not so good)

1. Set host list to be something like this:
``` elixir
:erlzk_conn.start_link([{'notahost.url', 2181}], ....)
```

2. running (with `iex -S mix`) will produce this output:
```
14:18:28.577 [error] Resolving 'notahost.url':2181 meet an error: :nxdomain
14:18:28.577 [error] Connect fail: :no_available_server, will be try again after 1000s
14:18:29.569 [error] Connect fail: :no_available_server, will be try again after 1000s
14:18:30.570 [error] Connect fail: :no_available_server, will be try again after 1000s
....
# this continues until the program is killed
```

## Cause
erlzk discards hosts if they fail to resolve
https://github.com/huaban/erlzk/blob/a1432aad2ebc33f4923dc5a885f8294cedbf9f39/src/erlzk_conn.erl#L367

When we try to establish a connection to zk, this branch is always hit:
https://github.com/huaban/erlzk/blob/a1432aad2ebc33f4923dc5a885f8294cedbf9f39/src/erlzk_conn.erl#L377

Followed by this error handler:
https://github.com/huaban/erlzk/blob/a1432aad2ebc33f4923dc5a885f8294cedbf9f39/src/erlzk_conn.erl#L450

## Ideas for fix
- We could add a check for list being empty after we resolve the servers in https://github.com/huaban/erlzk/blob/a1432aad2ebc33f4923dc5a885f8294cedbf9f39/src/erlzk_conn.erl#L165
- track how many errors we are encountering in some time interval and die if that goes to high.
   ie. allow a max of 30 errors in 60s

I'm curious to hear your thoughts.

**Comment by zolazhou** [comment]
Thank you for the detailed report.

Your ideas for fixing sounds good for me, and pull request is very welcomed.

**Comment by GlenWalker** [comment]
It might be worth tracking what type of error is returned by inet:gethostbyname (transient errors like timeouts, or permanent errors like nxdomain). If all calls to inet:gethostbyname return permanent errors then give up, but if all calls return transient errors then keep retrying, and if any calls succeed in resolving a name then continue.

When I made the changes related to DNS resolution, retrying etc in https://github.com/huaban/erlzk/pull/9 I tried to make the behaviour of erlzk similar to the Java library for ZooKeeper, so it might be worth reading through that to see if it gives any hints. If I have any time I'll take a look.

**Comment by zolazhou** [comment]
@GlenWalker That would be very nice, and thank you for your previous improvements to `erlzk` again.

**Comment by GlenWalker** [comment]
I think we should change resolve_server to return {ok, Result} or {error, Reason} rather than always a bare list. It should return {ok ,[]} only for {error, nxdomain} and return any others errors unchanged.

resolve_servers will need to be updated to handle the new {ok, Result} or {error, Reason} return from resolve_server, and also to return {ok, Result} or {error, Reason} instead of a bare list. It should return any errors from resolve_server immediately.

init will need to be updated to handle the new {ok, Result} or {error, Reason} return from resolve_servers and if {ok, []} or {error, Reason} are returned, it should return {stop, Reason} rather than continuing on to deduplicate and shuffle the list, and attempt to connect.

I think this behaviour is consistent with the Java implementation, and should fix the issue. I'll try to find time to make a pull request for this.

**Comment by GlenWalker** [comment]
Thanks! We should probably also tag this as v0.6.4 too, since I updated package.exs and erlzk.app.src to 0.6.4

**Comment by zolazhou** [comment]
@GlenWalker Yes, done. Really appreciated for your contribution.
